# Generated by Django 4.0.2 on 2022-02-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PowerConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOLT', models.IntegerField()),
                ('AMPERE_FOR_SECOND', models.FloatField()),
                ('CREATE_AT', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
