# Generated by Django 4.0.2 on 2022-02-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_observationlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.DateTimeField()),
                ('rnum', models.IntegerField(max_length=5)),
                ('stnId', models.IntegerField(max_length=3)),
                ('stnNm', models.CharField(max_length=6)),
                ('ta', models.FloatField(blank=True, max_length=6)),
                ('taQcflg', models.CharField(blank=True, max_length=1)),
                ('rn', models.FloatField(blank=True, max_length=6)),
                ('rnQcflg', models.CharField(blank=True, max_length=1)),
                ('ws', models.FloatField(blank=True, max_length=6)),
                ('wsQcflg', models.CharField(blank=True, max_length=1)),
                ('wd', models.IntegerField(blank=True, max_length=6)),
                ('wdQcflg', models.CharField(blank=True, max_length=1)),
                ('hm', models.IntegerField(blank=True, max_length=6)),
                ('hmQcflg', models.CharField(blank=True, max_length=1)),
                ('pv', models.FloatField(blank=True, max_length=6)),
                ('td', models.FloatField(blank=True, max_length=6)),
                ('pa', models.FloatField(blank=True, max_length=6)),
                ('paQcflg', models.CharField(blank=True, max_length=1)),
                ('ps', models.FloatField(blank=True, max_length=6)),
                ('psQcflg', models.CharField(blank=True, max_length=1)),
                ('ss', models.FloatField(blank=True, max_length=6)),
                ('ssQcflg', models.CharField(blank=True, max_length=1)),
                ('icsr', models.FloatField(blank=True, max_length=6)),
                ('dsnw', models.FloatField(blank=True, max_length=6)),
                ('hr3Fhsc', models.FloatField(blank=True, max_length=6)),
                ('dc10Tca', models.IntegerField(blank=True, max_length=6)),
                ('dc10LmcsCa', models.IntegerField(blank=True, max_length=6)),
                ('clfmAbbrCd', models.CharField(blank=True, max_length=4)),
                ('lcsCh', models.IntegerField(blank=True, max_length=2)),
                ('vs', models.IntegerField(blank=True, max_length=4)),
                ('gndSttCd', models.IntegerField(blank=True, max_length=2)),
                ('dmstMtphNo', models.FloatField(blank=True, max_length=4)),
                ('ts', models.FloatField(blank=True, max_length=6)),
                ('tsQcflg', models.CharField(blank=True, max_length=1)),
                ('m005Te', models.FloatField(blank=True, max_length=6)),
                ('m01Te', models.FloatField(blank=True, max_length=6)),
                ('m02Te', models.FloatField(blank=True, max_length=6)),
                ('m03Te', models.FloatField(blank=True, max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='observationlocation',
            name='location',
            field=models.CharField(max_length=6),
        ),
    ]
