# Generated by Django 4.0.2 on 2022-02-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_weather_alter_observationlocation_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='dc10LmcsCa',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dc10Tca',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='gndSttCd',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='hm',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lcsCh',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rnum',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='stnId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='vs',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wd',
            field=models.IntegerField(blank=True),
        ),
    ]
