# Generated by Django 4.0.2 on 2022-02-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_weather_dc10lmcsca_alter_weather_dc10tca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationlocation',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='observationlocation',
            name='update_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
