# Generated by Django 4.0.2 on 2022-02-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_clfmabbrcd_weather_clfm_abbrcd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='clfm_abbrCd',
            new_name='clfmabbrcd',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='dc10_lmcsCa',
            new_name='dc10lmcsca',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='dc10_tca',
            new_name='dc10tca',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='dmst_mtphNo',
            new_name='dmstmtphno',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='hm_qcflg',
            new_name='hmqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='hr3_fhsc',
            new_name='hr3fhsc',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='lcsCh',
            new_name='lcsch',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='m005_te',
            new_name='m005te',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='m01_te',
            new_name='m01te',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='m02_te',
            new_name='m02te',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='m03_te',
            new_name='m03te',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='pa_qcflg',
            new_name='paqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ps_qcflg',
            new_name='psqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='rn_qcflg',
            new_name='rnqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ss_qcflg',
            new_name='ssqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='stn_id',
            new_name='stnid',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='stn_nm',
            new_name='stnnm',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ta_qcflg',
            new_name='taqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ts_qcflg',
            new_name='tsqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='wd_qcflg',
            new_name='wdqcflg',
        ),
        migrations.RenameField(
            model_name='weather',
            old_name='ws_qcflg',
            new_name='wsqcflg',
        ),
    ]
