# Generated by Django 4.0.2 on 2022-02-14 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_gnd_sttcd_weather_gndsttcd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather',
            old_name='gndsttCd',
            new_name='gndsttcd',
        ),
    ]
