# Generated by Django 4.0.2 on 2022-02-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_gndsttcd_weather_gndsttcd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='tm',
            field=models.CharField(max_length=20),
        ),
    ]
