# Generated by Django 4.0.2 on 2022-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_weather_tm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='hmqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='paqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='psqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rnqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ssqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='taqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='tsqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wdqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wsqcflg',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
