# Generated by Django 4.0.2 on 2022-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_weather_hmqcflg_alter_weather_paqcflg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='clfmabbrcd',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dc10lmcsca',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dc10tca',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dmstmtphno',
            field=models.FloatField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dsnw',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='gndsttcd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='hm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='hr3fhsc',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='icsr',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lcsch',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='m005te',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='m01te',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='m02te',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='m03te',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pa',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ps',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pv',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='rn',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ss',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ta',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='td',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ts',
            field=models.FloatField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='vs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='ws',
            field=models.FloatField(max_length=6, null=True),
        ),
    ]
