# Generated by Django 4.0.2 on 2022-02-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_weather_clfmabbrcd_alter_weather_dc10lmcsca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='clfmabbrcd',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='dmstmtphno',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
