# Generated by Django 4.0.2 on 2022-02-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_alter_weather_clfmabbrcd_alter_weather_dmstmtphno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powerconsumption',
            name='AMPERE_FOR_SECOND',
        ),
        migrations.RemoveField(
            model_name='powerconsumption',
            name='BOLT',
        ),
        migrations.RemoveField(
            model_name='powerconsumption',
            name='CREATE_AT',
        ),
        migrations.AddField(
            model_name='powerconsumption',
            name='end_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='powerconsumption',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='powerconsumption',
            name='power_flag',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='powerconsumption',
            name='start_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='powerconsumption',
            name='watt',
            field=models.IntegerField(null=True),
        ),
    ]
