# Generated by Django 4.0.2 on 2022-02-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_remove_powerconsumption_ampere_for_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerconsumption',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
